service: fleet-vitals-backend
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

package:
  individually: true
  include:
    - dist/**
    - node_modules/**

functions:
  hello:
    handler: dist/handler.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline
